export type ContentType =
  | 'text/html'
  | 'text/plain'
  | 'text/xml'
  | 'image/jpeg'
  | 'image/gif'
  | 'image/png'
  | 'application/atom+xml'
  | 'application/json'
  | 'application/msword'
  | 'application/octet-stream'
  | 'application/pdf'
  | 'application/xhtml+xml'
  | 'application/xml'
  | 'application/x-www-form-urlencoded'
  | 'multipart/form-data'
